<?php

namespace AppBundle\Repository;

/**
 * CustomerOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
